### ISSUE TITLE
Create Hi-Fidelity Prototypes

### ISSUE THREAD

**Issue by OmegaHelix** [QuinnBast/SaskTel-Communication-Portal#19]

**Comment by QuinnBast** [comment]
![image](https://cdn.discordapp.com/attachments/509951877123932171/537407190810624029/JPEG_20190122_170414.jpg)

![image](https://cdn.discordapp.com/attachments/509951877123932171/539572799438716929/image0.jpg)

![image](https://cdn.discordapp.com/attachments/509951877123932171/539572841465643009/image0.jpg)

![image](https://cdn.discordapp.com/attachments/509951877123932171/539999274189062145/20190129_204350.jpg)

![image](https://cdn.discordapp.com/attachments/509951877123932171/539999274189062146/20190129_204401.jpg)

**Comment by QuinnBast** [comment]
Original prototypes:

![image](https://cdn.discordapp.com/attachments/509951877123932171/514991853209124864/20181121_203331.jpg)

![image](https://cdn.discordapp.com/attachments/509951877123932171/526103264568279050/unknown.png)
