### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by QuinnBast** [QuinnBast/SaskTel-Communication-Portal#35]
Frontend:
Selenium - testing html interfaces and button clicks - https://www.seleniumhq.org/
Mocha.js - testing for javascript modules - https://mochajs.org/
Enzyme: for testing React https://airbnb.io/enzyme/
Backend:
Postman - testing REST endpoints - https://www.getpostman.com/docs/v6/postman/scripts/test_scripts
unittest - Python unit testing - https://docs.python.org/2/library/unittest.html

**Comment by QuinnBast** [comment]
I think we have automated testing all setup in our project. We just need to implement tests as we go now. Suggest closing this?

**Comment by OmegaHelix** [comment]
Closing Due to these Frameworks being in place.
