### ISSUE TITLE
User Interface revamp

### ISSUE THREAD

**Issue by QuinnBast** [QuinnBast/SaskTel-Communication-Portal#57]
- [x] Implement ReactStrap
- [ ] User Profile section
- [x] Pagination/Carousel Body
- [ ] Theme: [Bootswatch.com](https://bootswatch.com) or [custom SASS](https://getbootstrap.com/docs/4.1/getting-started/theming/)

**Comment by QuinnBast** [comment]
I think this is completed or near completed with our current UI revamp progress?

**Comment by OmegaHelix** [comment]
Agreed, Revamped UI it's self is finished. Any further Changes are tracked in their related Issues.
